### ISSUE TITLE
共有ボタン追加

### ISSUE THREAD

**Issue by Uni-21** [nam-club/NumBuyer_front#121]
line, facebook, instagramが最低限あれば良さそう (これらはmaterial uiが使える)

**Comment by aoking1213** [comment]
https://zenn.dev/yurukei20/articles/5a7af661b2b89e

**Comment by aoking1213** [comment]
@UniTofu
game/finish_gameのレスポンスにplayerIdを追加してください。（Twitterの何位になったかの共有に必要）
