### ISSUE TITLE
背景を調整して文字を読みやすくする

### ISSUE THREAD

**Issue by aoking1213** [nam-club/NumBuyer_front#126]

**Comment by Uni-21** [comment]
@aoking1213 
下記は単一色でも良いのかなと思った。チュートリアル毎回作成し直すの面倒で申し訳ないが。。

- トップページの3つのボタンの背景
<img width="400" alt="Screen Shot 2022-10-29 at 17 21 35" src="https://user-images.githubusercontent.com/51052544/198821722-a44d24f8-5d8c-4cf8-b01a-e4b8fb9fe9d5.png">

- アビリティ選択の「アビリティを2つ選択してください」の背景
<img width="400" alt="Screen Shot 2022-10-29 at 17 22 24" src="https://user-images.githubusercontent.com/51052544/198821753-f679f4a2-bc38-45f7-ac13-48b02ab59f98.png">

- ゲーム画面の各種メッセージを表示する箇所の背景。  
 各種アビリティのメッセージは色を薄くするなどして文字が見やすいようにすれば画像でも良いのかなと思った
<img width="400" alt="Screen Shot 2022-10-29 at 17 27 54" src="https://user-images.githubusercontent.com/51052544/198821912-8fae48b7-e2a6-4337-99af-21e517b8bdfa.png">

**Comment by aoking1213** [comment]
あーしんどいなぁ
また1日かけて作り直さなくちゃ、、

**Comment by Uni-21** [comment]
だよねぇ
全部の画面のキャプチャ撮ってファイル置き換えるだけだったら自動化できそうだけど楽になる？
赤い線とかは多分無理だけど

**Comment by aoking1213** [comment]
赤い線は欲しいねぇ
メッセージ部分だけ前のキャプチャを切り取って貼ろうかな

**Comment by Uni-21** [comment]
赤い線は無理だけど作業時間半分くらいにはなると思うし今後のためにも作ってもええで
今後もUI変わるごとに1日取られるのはかなりきついから

それか、チュートリアルを実際のゲームの画面を開いて説明する形ができるならそれがベターかもな（実装大変そうだが）
