### ISSUE TITLE
カタストロフィ減った枚数表示できようにする

### ISSUE THREAD

**Issue by UniTofu** [nam-club/NumBuyer_front#88]
**バックエンド**
https://github.com/nam-club/NumBuyer_back/issues/99

**API**
updatestateのkey, valueを使う。
- keyにはcatastrophe.subtractedCoins
- toには発動された対象のプレイヤーID
- valueには減算された数字

が入る。
https://docs.google.com/spreadsheets/d/1hp18YKpLHtalW98dBsYN1FZiobg-8EeES_U8othOZsU/edit#gid=0&range=13:13

**Comment by aoking1213** [comment]
@UniTofu 
toとか指定せずに
playersの各playerにparameters:[{key: 'Coin fluctuation', value: '-20'}]のようにするのはどうでしょうか。
```
players [{
  playerId: (String)
  playerName:(String)
  cardNum:(int)
  coin:(int)
  parameters: [{
      key: (String)
      value: (String)
      abilityId: (String or null)
  }]
  firedAbilities: [{
    abilityId:(String)
    status:(String)
    type: (String)
    trigger: (String)
  }]
 } ]
```

**Comment by Uni-21** [comment]
いいでしょう。

**Comment by aoking1213** [comment]
https://github.com/nam-club/NumBuyer_front/issues/107
このissueで対応
